 "pegue os dados de um triangulo e verifique se o mesmo é equilatero, isosceles ou escaleno





algoritmo " exercicios trinagulos"
var
a, b, c : real
inicio
Escreval ("Quais os tres lados do triangulo?")
Leia (a)
Leia (b)
Leia (c)
Se ((A=B)e(B=C)) entao
Escreval(" Esse triangulo e equilatero")
Fimse
Se((A<>B)e(A<>C)e(B<>C)) entao
Escreval ("Esse triangulo e escaleno")
Senao
Escreval ("Essse triangulo e isosceles")
Fimse
fimalgoritmo